DROP TABLE IF EXISTS telefone CASCADE;
DROP TABLE IF EXISTS endereco CASCADE;
DROP TABLE IF EXISTS pessoa CASCADE;
DROP TABLE IF EXISTS pagamento CASCADE;
DROP TABLE IF EXISTS pessoa_endereco CASCADE;

CREATE TABLE pessoa(
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       nome VARCHAR(50) NOT NULL
);
ALTER TABLE pessoa ADD CONSTRAINT pk_pessoa PRIMARY KEY (id);
ALTER TABLE pessoa ADD CONSTRAINT uk_pessoa_nome UNIQUE (nome);


CREATE TABLE telefone(
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         pessoa_id BIGINT NOT NULL,
                         numero VARCHAR(100) NOT NULL
);

ALTER TABLE telefone ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE telefone ADD CONSTRAINT uk_telefone_pessoa_id UNIQUE (pessoa_id);
ALTER TABLE telefone ADD CONSTRAINT fk_telefone_pessoa_id FOREIGN KEY (pessoa_id) REFERENCES pessoa;


CREATE TABLE pagamento(
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          pessoa_id BIGINT NOT NULL,
                          valor DECIMAL NOT NULL
);

ALTER TABLE pagamento ADD CONSTRAINT pk_pagamento PRIMARY KEY (id);
ALTER TABLE pagamento ADD CONSTRAINT uk_pagamento_pessoa_id UNIQUE (pessoa_id);
ALTER TABLE pagamento ADD CONSTRAINT fk_pagamento_pessoa_id FOREIGN KEY (pessoa_id) REFERENCES pessoa;


CREATE TABLE endereco(
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         descricao VARCHAR(100) NOT NULL
);

ALTER TABLE endereco ADD CONSTRAINT pk_endereco PRIMARY KEY (id);


CREATE TABLE pessoa_endereco(
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                pessoa_id BIGINT NOT NULL,
                                endereco_id BIGINT NOT NULL
);

ALTER TABLE pessoa_endereco ADD CONSTRAINT pk_pessoa_endereco PRIMARY KEY (id);
ALTER TABLE pessoa_endereco ADD CONSTRAINT fk_pessoa_endereco_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa;
ALTER TABLE pessoa_endereco ADD CONSTRAINT fk_pessoa_endereco_endereco FOREIGN KEY (endereco_id) REFERENCES endereco;